rust/examples/kde_dolphin/Cargo.toml
rust/examples/kde_dolphin/build.rs
rust/examples/kde_dolphin/src/main.rs
rust/examples/kde_dolphin/ui/app.slint

The UI framework used in the KDE example was renamed from "sixtyfps" to "slint". This PR switches from the old name to the new name, as the Crates under the old name won't receive any update in the future.

Upgrade from sixtyfps to slint UI framework

---

rust/Cargo.toml
rust/src/builder.rs
rust/src/cancellation.rs
rust/src/connection.rs
rust/src/error.rs
rust/src/lib.rs
rust/src/message/auth_request.rs
rust/src/message/auth_response.rs
rust/src/message/error.rs
rust/src/message/kind.rs
rust/src/message/message_type.rs
rust/src/message/mod.rs
rust/src/message/state.rs
rust/src/message/upload_url.rs
rust/src/message/verdict.rs
rust/src/message/verdict_request.rs
rust/src/options.rs
rust/src/vaas.rs
rust/tests/real_api_integration_tests.rs

This PR refactors the Rust SDK quite a bit.
Key points are:
- No more "pull loops". Instead messaging between threads is used
- Removed the state machine as with the new protocol, there aren't as many message states as before
- Improved error handling for server errors and errors in threads

Improve rust sdk

---

typescript/npm-shrinkwrap.json
typescript/package.json
typescript/src/CancellationToken.ts
typescript/src/vaas.ts
typescript/tests/test.ts

This PR adds a cancellation token to the TypeScript SDK. With that token, it is possible to cancel a request to the VaaS API after a given time. The PR is not a breaking change, as a default value is set for all methods.

Add cancellation for typescript sdk

---

rust/src/error.rs

Make the `Error` type of the Rust SDK non-exhaustive. This prevents the public API from breaking, when we add a new error type. Else all downstream code would need to handle the new error type explicitly, instead of implicitly with a "catch all".

make the Error enum non-exhaustive

---

rust/examples/gscan/Cargo.toml
rust/examples/gscan/src/main.rs
rust/examples/kde_dolphin/Cargo.toml
rust/examples/kde_dolphin/src/main.rs

Fix all compilation errors in the Rust examples.
We should port the examples to the new OpenID API in the near future and add the examples to the CI workflow, such that we see, if they are breaking.

Repair examples

---

rust/src/vaas.rs
rust/tests/real_api_integration_tests.rs

Take references instead of values as ownership is not required. Take an `Url` instead of an `String` to enforce type safety.

Take references and Url in get_token

---

dotnet/Vaas/src/Vaas/Vaas.cs

* Throw VaasAuthenticationException instead of VaasClientException
* Use a separate HttpClient when uploading for the custom token

Dotnet: Fix authententication

---

php/src/vaas/Vaas.php

fopen() gets a file stream instead of reading the whole file content into memory.

use stream for file upload

---

dotnet/Vaas/src/Vaas/Messages/Detection.cs
dotnet/Vaas/src/Vaas/Messages/LibMagic.cs
dotnet/Vaas/src/Vaas/Messages/VerdictResponse.cs
dotnet/Vaas/src/Vaas/VaasVerdict.cs
dotnet/Vaas/test/Vaas.Test/IntegrationTests.cs

Dotnet implementation of #390

---

php/src/vaas/Message/Detection.php
php/src/vaas/Message/Error.php
php/src/vaas/Message/LibMagic.php
php/src/vaas/Message/ProblemDetails.php
php/src/vaas/Message/VaasVerdict.php
php/src/vaas/Message/VerdictResponse.php
php/src/vaas/Vaas.php
php/tests/vaas/VaasTest.php

PHP implementation of #390

---

typescript/src/Vaas.ts

dunno, this is just a proposal as we broke our heads about that today

proposal to make the forStream function more clear

---

java/src/main/java/de/gdata/vaas/Vaas.java

The JDK HttpClient has the questionable behavior of omitting the content-length if 0. This would be fine for the noBody publisher, but it does that for any body publisher (file, stream, ...).
Workaround: HTTP/2 allows the client to omit the content-length, HTTP 1.1 does not.

Java: Workaround for JDK HttpClient omitting content-length if 0

---

java/src/main/java/de/gdata/vaas/ClientCredentialsGrantAuthenticator.java
java/src/main/java/de/gdata/vaas/ResourceOwnerPasswordGrantAuthenticator.java
java/src/main/java/de/gdata/vaas/Vaas.java
java/src/main/java/de/gdata/vaas/messages/VerdictRequestForUrl.java
java/src/test/java/de/gdata/test/integration/RealApiIntegrationTests.java

Add authority check for forUrl to get a VaasClientException if it is a client side mistake

Add authority check for forUrl

---

java/.run/Test.run.xml
java/examples/VaasExample/build.gradle

Sometimes, gradle builds don't terminate. Investigation revealed that this is caused by gradle trying to upload a build scan (https://docs.gradle.org/current/userguide/build_scans.html) to gradle's servers. This may cause a ToS warning, which isn't answered by the IDE - hence gradle hangs.
The reason build scans are even uploaded in the first place is because we're setting the `--scan` flag by default. I propose we remove that and only upload build scans when explicitly configured to.
Also, the example was running on an outdated version of the SDK, update that as well (renovate is sleeping on this?)

java: Disable uploading build scans by default, update example dependencies

---

.github/workflows/ci-golang.yaml
golang/vaas/go.mod

the version in the go.mod file also pins the minimum version one has to have to use to use this library. Go 21 would also still be valid.

pin go to minor version

---

golang/vaas/pkg/vaas/vaas.go
golang/vaas/pkg/vaas/vaas_test.go

Hi, I've noticed that you silently drop non-seekable `io.ReadCloser`. Of course this can only happen in `ForStream` with zero content length, so maybe we should also add an early return for that case?

Fix silent drop of non-seekable ReadClosers

---

.github/workflows/ci-golang.yaml

Pushing actual Versions.
The previous workflow did not really push any versions to anywhere. 
Instead when you did `go get github.com/GDATASoftwareAG/vaas/golang/vaas` what you got is something like that:
```bash
go: downloading github.com/GDATASoftwareAG/vaas v0.1.0
go: downloading github.com/GDATASoftwareAG/vaas/golang/vaas v0.0.0-20240626115246-4901d29d086e
go: added github.com/GDATASoftwareAG/vaas/golang/vaas v0.0.0-20240626115246-4901d29d086e
```
With this PR the first "real" version is pushed and when now installing vaas via the same command, you will get this output:
```bash
go: downloading github.com/GDATASoftwareAG/vaas/golang/vaas v1.1.0
go: added github.com/GDATASoftwareAG/vaas/golang/vaas v1.1.0
```
You might ask, why I did not push a version v4.x.x which are is the actual …

Pushing actual versions

---

.github/workflows/ci-golang.yaml
golang/vaas/README.md
golang/vaas/examples/file-verdict-request/main.go
golang/vaas/examples/vaasctl/vaas.go
golang/vaas/pkg/vaas/vaas.go
golang/vaas/pkg/vaas/vaas_test.go

Right now it is not possible to cancel the socket initialization because the context that is passed via `Connect()` is also used for closing the socket. It is more idiomatic in golang to let the `VaaS` client implement the `io.Closer` interface and use that to close the connection explicitly.

Golang: Make VaaS client closeable

---

python/README.md
python/examples/VaasExample/main.py
python/examples/VaasExample/main_url.py
python/src/vaas/vaas.py

Since the Python SDK does not have enums like the other SDKs, I have added a short description in the Python Readme.md, as well as a short example in the respective examples.

Update Pythons scan function comments with return dict details

---

ruby/lib/vaas/vaas_main.rb
ruby/test/vaas_test.rb
ruby/vaas.gemspec

Upgrade some outdated dependencies, fix changed detection names, disable HTTP/2.
Part of #558

Ruby: Overall maintenance, disable HTTP/2

---

rust/tests/real_api_integration_tests.rs

The EICAR string detection name now has a suffix (as do most other detection names)

rust: Avoid test failures caused by changing detection names

---

rust/src/connection.rs

Also includes a refactor to consolidate code flows for file + streams. 
Part of #558

rust: Disable HTTP/2 in file + stream uploads

---

cpp/vaas.h

Forgot our beta SDK, let's do this here also

cpp: Enforce HTTP/1.1 in all requests (disable HTTP/2)

---

golang/vaas/pkg/vaas/vaas.go
golang/vaas/pkg/vaas/vaas_test.go
golang/vaas/pkg/vaas/web_socket_mock_test.go
golang/vaas/v2/pkg/vaas/vaas.go
golang/vaas/v2/pkg/vaas/vaas_test.go
golang/vaas/v2/pkg/vaas/web_socket_mock_test.go

Currently when WebSocket request fails the `sendRequest()` go routine terminates without consequences and the request itself will never be closed.

Fix stuck vaas request if websocket terminated

---

typescript/package.json
typescript/pnpm-lock.yaml
typescript/src/getTokenWithClientCredentialsGrant.ts
typescript/src/getTokenWithResourceOwnerPasswordGrant.ts
typescript/tests/test.ts

I found a way to get rid of the warning after jest run the integration tests:
1.  In case of axios, it seems like the default instances are still open after you get a response. A way to avoid this is by setting keepalive to false. If there are better ways to handle this, I am open for suggestions.
2. Some of our test are not able to close the Websocket properly, since we are also testing error cases. This results in some cases, where the Websocket was still open.

get rid of any open handles

---

golang/vaas/v2/pkg/vaas/vaas.go
golang/vaas/v2/pkg/vaas/web_socket_mock_test.go

* websocket pkg requires us to read and write only from 1 goroutine at a time
* code has to be structured to encourage this:
* authenticate runs first
* read/writePump goroutines get started after that
* run ping from writePump

Golang: Fix "WARNING: DATA RACE" #614
